### ISSUE TITLE
Humidity not passed

### ISSUE THREAD

**Issue by paulkoene** [PJCzx/homebridge-thermostat#11]
First of all great plugin, but I have a few things I would like to have included :) First of all the humidity seems to not be passing through to homekit. I don't see the value showing up while it is included in the script output. Below the current output. It also returns the air pressure which can be ignored.

{ "targetTemperature": 19, "temperature": 20, "humidity": 48.4, "pressure": 104546 }

**Comment by PJCzx** [comment]
Hello,

CurrentHumidity and TargetHumidity are currently managed by the plugin. Presure is not managed yet because apple is not expecting such a value. If you can tel me what the value for a thermostat to handle this, I will consider this or you can suggest a pull request. 

Finally, I played a bit with additional Characteristics and "Home" App is not that fancy when it comes to complex objects (only basic stuff are perfectly integrated for now. (eg speakers and displayed as "not managed" even if present in the documentation)

Best,
