### ISSUE TITLE
Heating state

### ISSUE THREAD

**Issue by paulkoene** [PJCzx/homebridge-thermostat#13]
First of all great plugin, but I have a few things I would like to have included :)

Homekit seems to have the option to indicate if the heating is actually running based on the targetTemperature and temperature. I have this information and can also supply it to homebridge-thermostat. It would be great if this was added.

**Comment by paulkoene** [comment]
My bad, this is actually already possible, I implemented it and homekit now correctly shows if the heating is running or not.

**Comment by PJCzx** [comment]
Yeah :) From my side I'd like Apple to clarify between targetState and currentState fro GUI perspective. If you set to Target Auto, the heating will be either Heating or Cooling depending of the temperature. This will display the Heating to Heat of Cool/Off instead of Auto Heating, Auto Cooling.... If you have an insight it will be welcomed.

Best,
PJ
