### ISSUE TITLE
Changing the mode from homebridge

### ISSUE THREAD

**Issue by lprhodes** [PJCzx/homebridge-thermostat#20]
Hey,

Using your code as a base I've gotten the HomeKit UI to update to say cooling or heating using `setCharacteristic(Characteristic.CurrentHeatingCoolingState, value)`

The problem is it only makes a difference to the temperature wording, not the Off/Heat/Cool/Auto mode switch.

Do you have any insight into this or how to fix it? I assume you see the same thing?

Thanks!

Luke

**Comment by lprhodes** [comment]
I fixed the above issue but unfortunately when the mode (HeatingCoolingState) is set using through pressing "Off" (which I have set as the default when homebridge starts) doesn't then call `setTargetHeatingCoolingState` until I've selected another mode on the Mode UI.

Steps:
- Run hombridge
- Mode UI is currently off due to being the default
- Set a temperature which in turn also calls `setCharacteristic(Characteristic.CurrentHeatingCoolingState, value)` and `setCharacteristic(CharacteristicTargetHeatingCoolingState, value)` with heat or cool depending on the temperature
- Mode UI shows the correct selected option (Heat or Cool)
- Pressing "Off" in the Mode UI does nothing
- Pressing Heat or Cool then pressing Off does work.

Looks like a HomeKit bug - do you know of any way to force it to reload the device or call `getCurrentHeatingCoolingState`/`getTargetHeatingCoolingState` again?

**Comment by lprhodes** [comment]
Note - using Siri to do the same thing works and calls `setTargetHeatingCoolingState` correctly so it's just the UI

**Comment by PJCzx** [comment]
Sorry I'm not very active since I tested my plugin for months without issues... i did a few tests in a "wireless" branch, maybe check it out you may see interesting stuff ? As many projects forked my code as a starting point, I'm afraid the issue is either temporary or from your side. To finish, my feeling about HomeKit is that it's work in progress, à soon as you want to go deeper in complex devices for exemple, the default interface is not working and you will need to use another app to deep test your code. I use "Home" to setup some stuff for instance.
