### ISSUE TITLE
dummy thermostat

### ISSUE THREAD

**Issue by elkorleone** [PJCzx/homebridge-thermostat#29]
Hi,

How can add a dummy thermostat in Homebridge? I want use it to set the target and use rules in EVE app

**Comment by PJCzx** [comment]
Hello @elkorleone,

Could you be more specific ? What are you trying to do and what part of the readme is not allowing you to do what you want?

Thx,
PJCzx

**Comment by PJCzx** [comment]
You even have a Fake API js that you can run with ```sudo node fake.js``` and provide ```apiroute :http://127.0.0.1```in your ```config.json```. Please provide a more consistent feedback and I will update the readme if necessary.

Best,
PJCzx

**Comment by elkorleone** [comment]
I want to have a thermostat in homebridge doing nothing. I mean, I want to set a temperature and use rules in EVE app like: If temperature is < turn this switch ON (other switch that i have working)
Really, I want to do a thermostat using an ESP8266 module and a relay but I dont find the solution

**Comment by elkorleone** [comment]
I have a NodeMCU with a RELAY + DHT22
Now, I use rules for automation but I cannot set a specific temperature (just turn ON/OFF)
If temperature is <21º after 17h and before 22h turn ON the relay
If temperature is =>21º after 17h and before 22h turn OFF the relay
I'm trying to find how to set a specific temperature and dont spend a lot of money in a Netatmo, Nest...

**Comment by PJCzx** [comment]
So what you want to do is broadly done with multiple tutorials on internet. It can both be achieved with arduino or raspberry (same or different). In any case, the thermostat need to expose an API as described and will be controlled by homebridge.

I can suggest you to have a look to this file within a branch of this project à worked on but I didn’t finished but in ANY CASE, document yourself since a few steps may be necessary to make it work that I have not fully documented.

https://github.com/PJCzx/homebridge-thermostat/blob/wirelessthermostat/temperaturehumidity.js

I wish you the best in your project and don’t hesitate to make pull request if necessary.

Best,
PJCzx
